### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by biggenius** [pylaligand/dart-sqlite#6]
#:~/tmp/dart-sqlite$ ./build.sh 
g++ -O2 -DDART_SHARED_LIB -I/home/biggenius/dart-sdk/include -rdynamic -fPIC -shared src/dart_sqlite.cc -lsqlite3 -o lib/libdart_sqlite.so
src/dart_sqlite.cc: In function ‘_Dart_Handle* dart_sqlite_Init(Dart_Handle)’:
src/dart_sqlite.cc:34:79: error: invalid conversion from ‘void (* (*)(Dart_Handle, int))(Dart_NativeArguments) {aka void (* (*)(_Dart_Handle*, int))(_Dart_NativeArguments*)}’ to ‘Dart_NativeEntryResolver {aka void (* (*)(_Dart_Handle*, int, bool*))(_Dart_NativeArguments*)}’ [-fpermissive]
In file included from src/dart_sqlite.cc:8:0:
src/dart_api.h:2244:25: error:   initializing argument 2 of ‘_Dart_Handle* Dart_SetNativeResolver(Dart_Handle, Dart_NativeEntryResolver)’ [-fpermissive]
src/dart_sqlite.cc: In function ‘void PrepareStatement(Dart_NativeArguments)’:
src/dart_sqlite.cc:129:107: error: invalid conversion from ‘void (*)(Dart_Handle, void*) {aka void (*)(_Dart_Handle*, void*)}’ to ‘intptr_t {aka long int}’ [-fpermissive]
src/dart_sqlite.cc:129:107: error: too few arguments to function ‘_Dart_WeakPersistentHandle* Dart_NewWeakPersistentHandle(Dart_Handle, void*, intptr_t, Dart_WeakPersistentHandleFinalizer)’
In file included from src/dart_sqlite.cc:8:0:
src/dart_api.h:466:39: note: declared here

Linux 3.8.0-34-generic Ubuntu  x86_64 x86_64 x86_64 GNU/Linux
Dart VM version: 1.3.0-dev.6.1 (Sat Mar 22 02:14:22 2014) on "linux_x64"

**Comment by pylaligand** [comment]
Fixed.
