### ISSUE TITLE
Library does not work when running inside docker container

### ISSUE THREAD

**Issue by gugahoi** [pylaligand/dart-sqlite#67]
Tried to run a script that imports `package:sqlite/sqlite.dart` inside google's latest docker dart image `google/dart` and it simply won't run with the following error:

```
libdart_sqlite.so: cannot open shared object file: No such file or directory
```

When doing the same steps outside of container on OS X, it all worked no problems.

**Comment by sandrobilbeisi** [comment]
also, be sure to run a 'pub get'
and
pub cache add sqlite

does your docker command list include a call to the Makefile ( i.e. 'make' ) ?
alternatively you can use the 'tool/download_shared_libraries' to obtain a precompiled sqlite binary for Linux ( also works for Mac OS X ; Windows is not supported at the moment )


export the path to your libdart_sqlite.so
export LD_LIBRARY_PATH=/mycleverpath/libdart_sqlite.so
( on Mac OS X it would be export DYLD_LIBRARY_PATH=/Users/*myusername*/.pub-cache/hosted/pub.dartlang.org/sqlite-0.4.2/lib/src )

**Comment by eunomiadev** [comment]
Same here on google app engine

**Comment by putraxor** [comment]
Ok, found the solution
So basically libsqlite3 is not installed on Docker by default, it can be checked with command:
```
ldd lib/src/libdart_sqlite.so
```

The solution:
```
FROM google/dart-runtime
USER root
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev
```
